#!/bin/bash
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$GOBIN:~/.npm-global/bin
sudo cp ~/.npm-global/bin/* /usr/local/bin/
git config --global user.name "$GIT_USERNAME"
git config --global user.email "$GIT_EMAIL"
cd ~/src/
stty stop '' -ixoff ; nvim $@
